# Configuration file for fraud detection pipeline

data:
  train_split: 0.7
  val_split: 0.15
  test_split: 0.15
  random_state: 42

features:
  categorical_columns:
    - ProductCD
    - card4
    - card6
    - P_emaildomain
    - R_emaildomain
  numerical_columns:
    - TransactionAmt
    - card1
    - card2
    - card3
    - card5
    - addr1
    - addr2
    - dist1
    - dist2

models:
  xgboost:
    n_trials: 50
    cv_folds: 5
  neural_network:
    hidden_layers: [128, 64, 32]
    dropout_rate: 0.3
    learning_rate: 0.001
    batch_size: 32
    epochs: 100
    patience: 10
